# کتابخانه ها

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization, Flatten

from sklearn.model_selection import StratifiedKFold

# تشخیص حملات در شبکه مدل 1

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/python 3_5/UNSW_NB15_training-set.csv')
df.head()

   id       dur proto service  ... ct_srv_dst  is_sm_ips_ports  attack_cat  label
0   1  0.121478   tcp       -  ...          1                0      Normal      0
1   2  0.649902   tcp       -  ...          6                0      Normal      0
2   3  1.623129   tcp       -  ...          6                0      Normal      0
3   4  1.681642   tcp     ftp  ...          1                0      Normal      0
4   5  0.449454   tcp       -  ...         39                0      Normal      0

[5 rows x 45 columns]

In [ ]:
df.shape

(175341, 45)

In [ ]:
df = df.drop('attack_cat', axis=1)
X = df.iloc[:,0:43]
Y = df.iloc[:,43]

In [ ]:
df

            id       dur proto  ... ct_srv_dst is_sm_ips_ports  label
0            1  0.121478   tcp  ...          1               0      0
1            2  0.649902   tcp  ...          6               0      0
2            3  1.623129   tcp  ...          6               0      0
3            4  1.681642   tcp  ...          1               0      0
4            5  0.449454   tcp  ...         39               0      0
...        ...       ...   ...  ...        ...             ...    ...
175336  175337  0.000009   udp  ...         24               0      1
175337  175338  0.505762   tcp  ...          1               0      1
175338  175339  0.000009   udp  ...         12               0      1
175339  175340  0.000009   udp  ...         30               0      1
175340  175341  0.000009   udp  ...         30               0      1

[175341 rows x 44 columns]

In [ ]:
print(X.shape)
print(Y.shape)

(175341, 43)
(175341,)

In [ ]:
df['proto'].value_counts()

tcp       79946
udp       63283
unas      12084
arp        2859
ospf       2595
          ...
egp          98
netblt       98
igmp         18
icmp         15
rtp           1
Name: proto, Length: 133, dtype: int64

In [ ]:
def str2int_X(X):  
  X1 = X.replace("tcp", 1)
  X2 = X1.replace("udp", 2)
  X3 = X2.replace("unas", 3)
  X4 = X3.replace("arp", 4)
  X5 = X4.replace("ospf", 5)
  X6 = X5.replace("sctp", 6)
  X7 = X6.replace("any", 7)
  X8 = X7.replace("gre", 8)
  X9 = X8.replace("rsvp", 9)
  X10 = X9.replace("ipv6", 10)
  X11 = X10.replace("sep", 11)
  X12 = X11.replace("sun-nd", 12)
  X13 = X12.replace("mobile", 13)
  X14 = X13.replace("swipe", 14)
  X15 = X14.replace("pim", 15)
  X16 = X15.replace("bbn-rcc", 16)
  X17 = X16.replace("prm", 17)
  X18 = X17.replace("xns-idp", 18)
  X19 = X18.replace("leaf-1", 19)
  X20 = X19.replace("pup", 20)
  X21 = X20.replace("ipnip", 21)
  X22 = X21.replace("xnet", 22)
  X23 = X22.replace("rdp", 23)
  X24 = X23.replace("ip", 24)
  X25 = X24.replace("egp", 25)
  X26 = X25.replace("leaf-2", 26)
  X27 = X26.replace("iso-tp4", 27)
  X28 = X27.replace("trunk-1", 28)
  X29 = X28.replace("chaos", 29)
  X30 = X29.replace("trunk-2", 30)
  X31 = X30.replace("nvp", 31)
  X32 = X31.replace("st2", 32)
  X33 = X32.replace("cbt", 33)
  X34 = X33.replace("igp", 34)
  X35 = X34.replace("mux", 35)
  X36 = X35.replace("irtp", 36)
  X37 = X36.replace("argus", 37)
  X38 = X37.replace("dcn", 38)
  X39 = X38.replace("emcon", 39)
  X40 = X39.replace("netblt", 40)
  X41 = X40.replace("ggp", 41)
  X42 = X41.replace("hmp", 42)
  X43 = X42.replace("gmtp", 43)
  X44 = X43.replace("visa", 44)
  X45 = X44.replace("br-sat-mon", 45)
  X46 = X45.replace("tp++", 46)
  X47 = X46.replace("mtp", 47)
  X48 = X47.replace("wsn	", 48)
  X49 = X48.replace("zero", 49)
  X50 = X49.replace("nsfnet-igp", 50)
  X51 = X50.replace("etherip", 51)
  X52 = X51.replace("snp", 52)
  X53 = X52.replace("ipip", 53)
  X54 = X53.replace("cftp", 54)
  X55 = X54.replace("pri-enc", 55)
  X56 = X55.replace("crudp", 56)
  X57 = X56.replace("wb-mon", 57)
  X58 = X57.replace("ptp", 58)
  X59 = X58.replace("sdrp", 59)
  X60 = X59.replace("ippc", 60)
  X61 = X60.replace("fc", 61)
  X62 = X61.replace("pvp", 62)
  X63 = X62.replace("ipv6-frag", 63)
  X64 = X63.replace("iplt", 64)
  X65 = X64.replace("ipcv", 65)
  X66 = X65.replace("kryptolan", 66)
  X67 = X66.replace("compaq-peer", 67)
  X68 = X67.replace("skip", 68)
  X69 = X68.replace("secure-vmtp	", 69)
  X70 = X69.replace("idpr", 70)
  X71 = X70.replace("smp", 71)
  X72 = X71.replace("sat-expak", 72)
  X73 = X72.replace("ipx-n-ip", 73)
  X74 = X73.replace("larp", 74)
  X75 = X74.replace("pnni", 75)
  X76 = X75.replace("stp", 76)
  X77 = X76.replace("ipv6-route", 77)
  X78 = X77.replace("idpr-cmtp", 78)
  X79 = X78.replace("vrrp", 79)
  X80 = X79.replace("sprite-rpc", 80)
  X81 = X80.replace("wb-expak	", 81)
  X82 = X81.replace("iso-ip", 82)
  X83 = X82.replace("idrp", 83)
  X84 = X83.replace("crtp", 84)
  X85 = X84.replace("pgm", 85)
  X86 = X85.replace("isis", 86)
  X87 = X86.replace("aes-sp3-d", 87)
  X88 = X87.replace("tlsp", 88)
  X89 = X88.replace("scps", 89)
  X90 = X89.replace("tcf", 90)
  X91 = X90.replace("ddp", 91)
  X92 = X91.replace("rvd", 92)
  X93 = X92.replace("sat-mon", 93)
  X94 = X93.replace("merit-inp", 94)
  X95 = X94.replace("qnx", 95)
  X96 = X95.replace("l2tp", 96)
  X97 = X96.replace("ddx", 97)
  X98 = X97.replace("ipv6-opts", 98)
  X99 = X98.replace("encap", 99)
  X100 = X99.replace("sps", 100)
  X101 = X100.replace("sm", 101)
  X102 = X101.replace("i-nlsp", 102)
  X103 = X102.replace("vmtp", 103)
  X104 = X103.replace("il", 104)
  X105 = X104.replace("ifmp", 105)
  X106 = X105.replace("a/n", 106)
  X107 = X106.replace("srp", 107)
  X108 = X107.replace("3pc", 108)
  X109 = X108.replace("eigrp", 109)
  X110 = X109.replace("narp", 110)
  X111 = X110.replace("micp", 111)
  X112 = X111.replace("ipcomp", 112)
  X113 = X112.replace("bna", 113)
  X114 = X113.replace("dgp", 114)
  X115 = X114.replace("iatp", 115)
  X116 = X115.replace("mfe-nsp", 116)
  X117 = X116.replace("ax.25", 117)
  X118 = X117.replace("mhrp", 118)
  X119 = X118.replace("ipv6-no", 119)
  X120 = X119.replace("sccopmce", 120)
  X121 = X120.replace("aris", 121)
  X122 = X121.replace("ttp", 122)
  X123 = X122.replace("uti", 123)
  X124 = X123.replace("xtp", 124)
  X125 = X124.replace("cphb", 125)
  X126 = X125.replace("vines", 126)
  X127 = X126.replace("fire", 127)
  X128 = X127.replace("cpnx", 128)
  X129 = X128.replace("pipe", 129)
  X130 = X129.replace("ib", 130)
  X131 = X130.replace("igmp", 131)
  X132 = X131.replace("-", 132)
  X133 = X132.replace("dns", 133)
  X134 = X133.replace("http", 134)
  X135 = X134.replace("ftp", 135)
  X136 = X135.replace("ftp-data", 136)
  X137 = X136.replace("pop3", 137)
  X138 = X137.replace("ssh", 138)
  X139 = X138.replace("ssl", 139)
  X140 = X139.replace("snmp", 140)
  X141 = X140.replace("dhcp", 141)
  X142 = X141.replace("radius", 142)
  X143 = X142.replace("irc", 143)
  X144 = X143.replace("smtp", 144)
  X145 = X144.replace("FIN", 145)
  X146 = X145.replace("INT", 146)
  X147 = X146.replace("CON", 147)
  X148 = X147.replace("REQ", 148)
  X149 = X148.replace("ACC", 149)
  X150 = X149.replace("CLO", 150)
  X151 = X150.replace("RST", 151)
  X152 = X151.replace("wsn", 152)
  X153 = X152.replace("wb-expak", 153)
  X154 = X153.replace("secure-vmtp", 154)
  X155 = X154.replace("icmp", 155)
  X156 = X155.replace("rtp", 156)
  X157 = X156.replace("ECO", 157)
  X158 = X157.replace("PAR", 158)
  X159 = X158.replace("URN", 159)
  X160 = X159.replace("no", 160)

  return X160

In [ ]:
X = str2int_X(X)

In [ ]:
X

            id       dur  proto  ...  ct_src_ltm  ct_srv_dst  is_sm_ips_ports
0            1  0.121478      1  ...           1           1                0
1            2  0.649902      1  ...           1           6                0
2            3  1.623129      1  ...           2           6                0
3            4  1.681642      1  ...           2           1                0
4            5  0.449454      1  ...           2          39                0
...        ...       ...    ...  ...         ...         ...              ...
175336  175337  0.000009      2  ...          24          24                0
175337  175338  0.505762      1  ...           1           1                0
175338  175339  0.000009      2  ...           3          12                0
175339  175340  0.000009      2  ...          30          30                0
175340  175341  0.000009      2  ...          30          30                0

[175341 rows x 43 columns]

In [ ]:
model = Sequential()

model.add(Dense(128, input_dim=43 ,kernel_initializer="uniform", activation="relu"))

model.add(Dense(128, kernel_initializer="uniform", activation="relu"))

model.add(Dense(128, kernel_initializer="uniform", activation="relu"))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Dense(64, kernel_initializer="uniform", activation="relu"))
model.add(BatchNormalization())

model.add(Dense(1, kernel_initializer="uniform", activation="sigmoid"))

In [ ]:
model.compile(loss = "binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
model.fit(x=X ,y=Y , epochs=5, batch_size=128)

Epoch 1/5
1370/1370 [==============================] - 9s 6ms/step - loss: 0.3936 - accuracy: 0.7960
Epoch 2/5
1370/1370 [==============================] - 8s 6ms/step - loss: 0.3506 - accuracy: 0.8402
Epoch 3/5
1370/1370 [==============================] - 8s 6ms/step - loss: 0.3365 - accuracy: 0.8517
Epoch 4/5
1370/1370 [==============================] - 8s 6ms/step - loss: 0.3297 - accuracy: 0.8559
Epoch 5/5
1370/1370 [==============================] - 8s 6ms/step - loss: 0.3243 - accuracy: 0.8573

In [ ]:
######################################################################################################################################

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/Datasets/python 3_5/UNSW_NB15_testing-set.csv')
df2.head()

   id       dur proto service  ... ct_srv_dst  is_sm_ips_ports  attack_cat  label
0   1  0.000011   udp       -  ...          2                0      Normal      0
1   2  0.000008   udp       -  ...          2                0      Normal      0
2   3  0.000005   udp       -  ...          3                0      Normal      0
3   4  0.000006   udp       -  ...          3                0      Normal      0
4   5  0.000010   udp       -  ...          3                0      Normal      0

[5 rows x 45 columns]

In [ ]:
df2.shape

(82332, 45)

In [ ]:
df2 = df2.drop('attack_cat', axis=1)
X2 = df2.iloc[:,0:43]
Y2 = df2.iloc[:,43]

In [ ]:
print(X2.shape)
print(Y2.shape)

(82332, 43)
(82332,)

In [ ]:
X2 = str2int_X(X2)

In [ ]:
model.evaluate(X2, Y2)

2573/2573 [==============================] - 8s 3ms/step - loss: 0.5167 - accuracy: 0.7567

[0.5167153477668762, 0.7567167282104492]